

from sequence_manipulation import GC_content
from sequence_manipulation import nucleotide_composition
from sequence_manipulation import nucleotide_count
from sequence_manipulation import RNA_transcription
from sequence_manipulation import DNA_translation

#sequence_manipulation\GC_content.py
GC_content = GC_content.GC_content

#sequence_manipulation\nucleotide_composition.py
total_nucleotide_composition = nucleotide_composition.total_nucleotide_composition
nucleotide_composition = nucleotide_composition.nucleotide_composition

#sequence_manipulation\nucleotide_count.py
total_nucleotide_count = nucleotide_count.total_nucleotide_count
nucleotide_count = nucleotide_count.nucleotide_count

#sequence_manipulation\RNA_transcription.py
transcription = RNA_transcription.transcription

#sequence_manipulation\DNA_translation.py
translation = DNA_translation.translation